#!/usr/bin/env bash
# Generated by workshop-publisher from workshop-config.yaml.
# Re-run workshop-publish to update this file.

set -euo pipefail

UV_VERSION=0.11.14
UV_BIN="$HOME/.local/bin/uv"
UV_INSTALL_URL="https://astral.sh/uv/install.sh"

if [ -n "$UV_VERSION" ]; then
  UV_INSTALL_URL="https://astral.sh/uv/$UV_VERSION/install.sh"
fi

INSTALL_UV=0
if [ ! -x "$UV_BIN" ]; then
  INSTALL_UV=1
elif [ -n "$UV_VERSION" ] && [ "$("$UV_BIN" --version | awk '{print $2}')" != "$UV_VERSION" ]; then
  INSTALL_UV=1
fi

if [ "$INSTALL_UV" = "1" ]; then
  curl -LsSf "$UV_INSTALL_URL" | env UV_INSTALL_DIR="$HOME/.local/bin" UV_NO_MODIFY_PATH=1 sh
fi

export PATH="$HOME/.local/bin:$PATH"

if [ -n "$UV_VERSION" ]; then
  ACTUAL_UV_VERSION="$(uv --version | awk '{print $2}')"
  if [ "$ACTUAL_UV_VERSION" != "$UV_VERSION" ]; then
    echo "Expected uv $UV_VERSION, found $ACTUAL_UV_VERSION."
    echo "Re-run workshop-publish locally with the uv version that should generate uv.lock."
    exit 1
  fi
fi

if [ ! -f pyproject.toml ]; then
  echo "pyproject.toml is missing; re-run workshop-publish locally and commit the generated environment files."
  exit 1
fi

if [ ! -f uv.lock ]; then
  echo "uv.lock is missing; re-run workshop-publish locally and commit the generated lockfile."
  exit 1
fi

uv lock --check --no-config
uv sync --locked --no-config

uv run python -m ipykernel install --user --name newsroom-infrastructure-for-ai-experimentation --display-name 'Newsroom Infrastructure for AI Experimentation'

if [ -n "${CODESPACE_NAME:-}" ] && command -v gh >/dev/null 2>&1; then
  gh codespace ports visibility 7860:public 7861:public 8501:public 8502:public 8503:public -c "$CODESPACE_NAME" || \
    echo "Warning: could not set Codespaces port visibility"
fi

