#!/usr/bin/env bash
# Generated by workshop-publisher from workshop-config.yaml.
# Re-run workshop-publish to update this file.

set -euo pipefail

if ! command -v uv >/dev/null 2>&1; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi

export PATH="$HOME/.local/bin:$PATH"

if [ ! -f pyproject.toml ]; then
  echo "pyproject.toml is missing; re-run workshop-publish locally and commit the generated environment files."
  exit 1
fi

if [ ! -f uv.lock ]; then
  echo "uv.lock is missing; re-run workshop-publish locally and commit the generated lockfile."
  exit 1
fi

uv lock --check
uv sync --locked

uv run python -m ipykernel install --user --name newsroom-infrastructure-for-ai-experimentation --display-name 'Newsroom Infrastructure for AI Experimentation'

if [ -n "${CODESPACE_NAME:-}" ] && command -v gh >/dev/null 2>&1; then
  gh codespace ports visibility 7860:public 7861:public 8501:public 8502:public 8503:public -c "$CODESPACE_NAME" || \
    echo "Warning: could not set Codespaces port visibility"
fi

